# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FMPhoneTextField-Example' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FMPhoneTextField-Example

  pod 'FMPhoneTextField', :path => "../FMPhoneTextField/"

end
